apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helloworld-svc-deployment.yaml
- helloworld-svc-service.yaml
- helloworld-svc-route.yaml
- helloworld-gui-deployment.yaml
- helloworld-gui-service.yaml
- helloworld-gui-route.yaml
images:
- name: ghcr.io/k8s-gitops-lab/helloworld-svc
  newTag: v1.0.1
- name: ghcr.io/k8s-gitops-lab/helloworld-gui
  newTag: v1.0.1
