apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helloworld-svc-deployment.yaml
- helloworld-svc-service.yaml
- helloworld-svc-route.yaml
- helloworld-gui-deployment.yaml
- helloworld-gui-service.yaml
- helloworld-gui-route.yaml
images:
- name: helloworld-svc
  newName: elkouhen/helloworld-svc
  newTag: latest
- name: helloworld-gui
  newName: elkouhen/helloworld-gui
  newTag: latest
- name: registry.registry.svc.cluster.local:5000/helloworld-svc
  newTag: v1.0.0
- name: registry.registry.svc.cluster.local:5000/helloworld-gui
  newTag: v1.0.0
