apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helloworld-svc-deployment.yaml
- helloworld-svc-service.yaml
- helloworld-svc-route.yaml
- helloworld-gui-deployment.yaml
- helloworld-gui-service.yaml
- helloworld-gui-route.yaml
images:
- name: registry.registry.svc.cluster.local:5000/helloworld-svc
  newTag: 7c3db9b6
- name: registry.registry.svc.cluster.local:5000/helloworld-gui
  newTag: 7c3db9b6
